### ISSUE TITLE
White Background on Asana Tasks

### ISSUE THREAD

**Issue by Koolstr** [pavel-agarkov/Midnight-Lizard#56]
I'm a heavy Asana.com user, and I have Midnight Lizard set up to a pitch black theme with hacker green text. When working on a project, when I hover my mouse over any one of the tasks, the black background changes to pure white. Worse, the text does not change color, and light green on white is practically impossible to read.

I've been fiddling with the settings and can't seem to find anything that affects this or that can fix it. I believe it is a bug. Please look into this, or let me know what settings need to be changed for the background to not go completely, blindingly white on hover. Thanks.

**Comment by Koolstr** [comment]
I've noticed this is an issue on Google's account selection page too (when you have multiple Google accounts signed in the browser and you try to connect an app to your social account).

**Comment by pavel-agarkov** [comment]
commenting to dig deeper later.
asana.com style causing the problem:
```css
.TaskRow.ItemRow--enabled:not(.ItemRow--focused):not(.ItemRow--highlighted):hover {
    background-color: #f6f8f9;
}
```
